config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cards do
    collection do
      get :break_the_ice
      get :exposed
      get :risky_business
      get :lets_get_edgy
      get :play_it_safe
      get :custom
      get :saved
    end
    member do
      patch :add
    end
  end


  root to: 'cards#home'
  get '/user' => 'cards#index', :as => :user_root

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home; end

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(restaurant_params)
    @card.save
    redirect_to cards_path
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    @card.update(restaurant_params)

    redirect_to :custom_cards
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to request.referrer || default_path
  end

  def break_the_ice
    @cards = Card.where(genre: 'Break the ice')
  end

  def exposed
    @cards = Card.where(genre: 'Exposed')
  end

  def risky_business
    @cards = Card.where(genre: 'Risky Business')
  end

  def lets_get_edgy
    @cards = Card.where(genre: "Let's Get Edgy")
  end

  def play_it_safe
    @cards = Card.where(genre: 'Play It Safe')
  end

  def custom
    @cards = Card.where(genre: 'Custom')
  end

  def saved
    @cards = Card.where(favorite: true)
  end

  def add
    @card = Card.find(params[:id])

    @card.update(favorite: !@card.favorite)
    redirect_to request.referrer || default_path
  end


  private
  def restaurant_params
    params.require(:card).permit(:content, :genre, :favorite)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/break_the_ice.html.erb
<div class='cards'>
  <% @cards.each do |card| %>
    <div class='card-show'>
      <p><%= card.content %></p>
      <% if card.favorite == true %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-regular fa-bookmark"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cards/custom.html.erb
<div class='cards'>
    <% @cards.each do |card| %>
      <div class='card-show'>
        <p><%= card.content %></p>
        <%= link_to 'Edit', edit_card_path(card), style:"text-decoration:none" %> <!-- Assuming you have a corresponding edit action -->
        <%= link_to "Delete", card_path(card), method: :delete, data: { confirm: "Are you sure?" }, style:"text-decoration:none" %>
      </div>
      <% end  %>
</div>

app/views/cards/edit.html.erb
<div class="form-container">
  <div class="form">
    <%= simple_form_for @card, url: card_path(@card), method: :patch do |f| %>
      <%= f.input :content, input_html: { style: 'height: 170px;' }%>

      <%# <%= f.input :genre, collection: ['Break the ice', 'Exposed', 'Risky Business', "Let's Get Edgy", 'Play it Sage', 'Custom'], prompt: "Choose a genre", selected: @card.genre %>

      <%= f.button :submit, 'Update', class: 'btn-create' %>
    <% end %>
  </div>
</div>

app/views/cards/exposed.html.erb
<div class='cards'>
  <% @cards.each do |card| %>
    <div class='card-show'>
      <p><%= card.content %></p>
      <% if card.favorite == true %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-regular fa-bookmark"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cards/home.html.erb
<div class="landing-page">
  <div class="landing-header">
    <h1>Have better conversations with Faros</h1>
    <%= link_to "Get started", new_user_registration_path, class: 'btn-started' %>
  </div>

  <div class="composition">
    <div class="composition__photo composition__photo--p1">
      <h2>What would you do with $1,000?</h2>
    </div>

    <div class="composition__photo composition__photo--p2">
      <h2>What side of you am I yet to see?</h2>
    </div>

    <div class="composition__photo composition__photo--p3">
      <h2>What do you think I take for granted?</h2>
    </div>
  </div>
</div>




<%# <div class="container">
    <div class="welcome">
        <h1>🌟 Hey there, Welcome to Faros! 🌟</h1>
    </div>
    <div class="content">
        <p>Get ready to spice up your chats with Faros cards! We're all about making conversations super fun and way more meaningful. Whether you're hanging out with old friends or meeting new people, our cards have got your back.</p>

        <h2>What's in it for you?</h2>
        <ul>
            <li><strong>Cool Topics:</strong> From quirky facts about you to deep, mind-bending questions – we've got a mix of everything.</li>
            <li><strong>Real Connections:</strong> Forget small talk. Our cards help you dive deeper and really get to know people.</li>
            <li><strong>For Everyone:</strong> Whether you're a talkative person or a bit shy, our cards are super easy and fun for all.</li>
        </ul>

        <p>Grab a card, start chatting, and watch the magic happen with Faros – your go-to for awesome conversations!</p>
    </div>
</div> %>

  <%# <div class="home-pic">
    <%= image_tag('friends') %>
  <%# </div> %>

app/views/cards/index.html.erb
<div class="landing-info">
  <div class="decks">
    <div class="deck exposed">
      <h2><%= link_to 'Exposed', exposed_cards_path  %></h2>
    </div>

    <div class="deck break-the-ice">
      <h2><%= link_to 'Break The Ice', break_the_ice_cards_path %></h2>
    </div>

    <div class="deck risky_business">
      <h2><%= link_to 'Risky Business', risky_business_cards_path %></h2>
    </div>

    <div class="deck edgy">
      <h2><%= link_to "Let's Get Edgy", lets_get_edgy_cards_path %></h2>
    </div>

    <div class="deck play_safe">
      <h2><%= link_to 'Play It Safe', play_it_safe_cards_path %></h2>
    </div>

    <div class="deck custom">
      <h2><%= link_to 'Custom Cards', custom_cards_path %></h2>
    </div>
  </div>
</div>

app/views/cards/lets_get_edgy.html.erb
<div class='cards'>
  <% @cards.each do |card| %>
    <div class='card-show'>
      <p><%= card.content %></p>
      <% if card.favorite == true %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-regular fa-bookmark"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cards/new.html.erb
  <div class="form-container">
    <div class="form">
      <%= simple_form_for @card do |f| %>
        <%= f.input :content, input_html: { style: 'height: 170px;', maxlength: 80}%>

        <%= f.input :genre, collection: ['Break the ice', 'Exposed', 'Risky Business', "Let's Get Edgy", 'Play it Sage', 'Custom'], prompt: "Choose a genre" %>

        <%= f.button :submit, class: 'btn-create' %>
      <% end %>
    </div>
  </div>

app/views/cards/play_it_safe.html.erb
<div class='cards'>
  <% @cards.each do |card| %>
    <div class='card-show'>
      <p><%= card.content %></p>
      <% if card.favorite == true %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-regular fa-bookmark"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cards/risky_business.html.erb
<div class='cards'>
  <% @cards.each do |card| %>
    <div class='card-show'>
      <p><%= card.content %></p>
      <% if card.favorite == true %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-solid fa-bookmark"></i>
        <% end %>
      <% else %>
        <%= link_to add_card_path(card), method: :patch, class: 'favorite-icon' do %>
          <i style="color: grey;" class="fa-regular fa-bookmark"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cards/saved.html.erb
<div class='cards'>
  <% @cards.each do |card| %>
    <div class='card-show'>
      <p><%= card.content %></p>
    </div>
  <% end  %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;700&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>

    <%# <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to cards_path, class: "navbar-brand" do %>
      <%= image_tag "faroscopy.jpg", class:'nav-logo' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Saved', saved_cards_path, class:'saved_btn' %>
            <%= link_to 'Create card', new_card_path, class:'create_btn' %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav_link" %>
          </li>
          <li class="nav-item">
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav_link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>